# Generated by Django 3.1.3 on 2020-12-07 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('idClient', models.IntegerField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=45)),
                ('secondName', models.CharField(max_length=45)),
                ('phoneNumber', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('idMatch', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('idPlace', models.IntegerField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=10)),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('idTeam', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.client')),
                ('idMatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.match')),
                ('idPlace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.place')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='idTeam1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team1', to='tickets.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='idTeam2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Team2', to='tickets.team'),
        ),
    ]
