# Generated by Django 3.1.3 on 2021-01-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('second_name', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=10)),
                ('row', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('id_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ticket', to='tickets.client')),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_ticket', to='tickets.match')),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_ticket', to='tickets.place')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='id_team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='tickets.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='id_team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='tickets.team'),
        ),
    ]
